---
title: "plink PCA"
author: "Nikolaos Tourvas"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    code_download: true
    code_folding: show
    theme: default
    toc: true
    toc_float: true
    keep_md: true
  word_document:
    toc: true
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, include=TRUE, cache=FALSE,
                      dev = c("png", "pdf", "svg"), dpi = 300)
```

# Load libraries
```{r}
library(tidyverse)
```

# Read and manipulate data
Read data
```{r}
# read in data
pca <- read_table2("../results/Phalepensis_pruned.eigenvec", col_names = FALSE)
eigenval <- scan("../results/Phalepensis_pruned.eigenval")
```

Data wrangling
```{r}
# sort out the pca data
# remove nuisance column
pca <- pca[,-1]
# set names
names(pca)[1] <- "ind"
names(pca)[2:ncol(pca)] <- paste0("PC", 1:(ncol(pca)-1))
```

Add strata information (Genotype, Population, Region)
```{r}
# load strata information
strata <- read.csv("../data/strata.csv", stringsAsFactors = TRUE)

pca$ind <- strata$Genotype

pca <- as_tibble(data.frame(pca, strata[,c(2:4)]))
```

Calculate the percentage variance explained
```{r}
# first convert to percentage variance explained
pve <- data.frame(PC = 1:20, pve = eigenval/sum(eigenval)*100)

# calculate the cumulative sum of the percentage variance explained
cumsum(pve$pve)
```

# Plots
Screeplot
```{r screeplot, fig.height=3, fig.width=3, dpi=300}
variance_pca_plot <- ggplot(pve, aes(x=PC, y=pve))+
  geom_line(group=1)+
  geom_point(size=2)+
  theme_bw() +
  scale_x_continuous(breaks = seq(1, 20, 3)) +
  xlab("Axis") +
  ylab("Explained variance (%)")

variance_pca_plot
```

PCA plot
```{r PCA, fig.width=7, fig.height=5, dpi=300}
pca_p <- ggplot(data=pca, aes(x=PC1, y=PC2, label=ind)) +
  geom_point(aes(color=Population, shape=Region), size=3) +
  theme_bw() +
  xlab(paste("PC1 - ", round(pve$pve[1], 2), "%", sep="")) +
  ylab(paste("PC2 - ", round(pve$pve[2], 2), "%", sep="")) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme(axis.title = element_text(size = 9))
  
pca_p
```

PCA plot PC3 and PC4
```{r PCA_34, fig.width=7, fig.height=7, dpi=300}
pca34_p <- ggplot(data=pca, aes(x=PC3, y=PC4, label=ind)) +
  geom_point(aes(color=Population, shape=Region), size=3) +
  theme_bw() +
  xlab(paste("PC3 - ", round(pve$pve[3], 2), "%", sep="")) +
  ylab(paste("PC4 - ", round(pve$pve[4], 2), "%", sep="")) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme(axis.title = element_text(size = 9))
  
pca34_p
```